name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  game_package:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

 

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/ 
    - assets/audio/ 
 
flutter_gen:
  localization:
    enabled: true
    synthetic-package: true
    arb-dir: ../lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart